menu title AM64x SD extlinux Rehearsal
timeout 30
default AM64x_SD

label AM64x_SD
    kernel /boot/Image
    fdt /boot/dtb/ti/k3-am642-sk.dtb
    append console=ttyS2,115200n8 earlycon=ns16550a,mmio32,0x02800000 root=PARTUUID=076c4a2a-02 rw rootfstype=ext4 rootwait
