menu title AM64x USB extlinux Rehearsal
timeout 30
default AM64x_USB

label AM64x_USB
    kernel /Image
    fdt /k3-am642-sk.dtb
    append console=ttyS2,115200n8 earlycon=ns16550a,mmio32,0x02800000 root=PARTUUID=2bcf5ad2-03 rw rootfstype=ext4 rootwait rootdelay=30 loglevel=8 ignore_loglevel
